//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vegetais.Blog.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndiqueUmAmigo
    {
        public int Id { get; set; }
        public string MeuNome { get; set; }
        public string MeuEmail { get; set; }
        public string AmigoNome { get; set; }
        public string AmigoEmail { get; set; }
        public System.DateTime DataDeEnvio { get; set; }
    }
}
