//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vegetais.Blog.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Artigo
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Imagem { get; set; }
        public string Video { get; set; }
        [AllowHtml, UIHint("tinymce_jquery_full")]
        public string Conteudo { get; set; }
        public string Permalink { get; set; }
        public bool SoParaAssinantes { get; set; }
        public System.DateTime DataDePublicacao { get; set; }
        public string Autor { get; set; }
        public string Categoria { get; set; }
    }
}
